### ISSUE TITLE
How to Join the Team

### ISSUE THREAD

**Issue by ahoefling** [livecoders/Home#1]
With inspiration from James Montemagno I started a new live coding stream [https://www.twitch.tv/ahoefling](https://www.twitch.tv/ahoefling) and I am planning to run my stream once a week (most likely on Monday or Tuesday afternoons). 

Is the live coders team going to include community members? If community members are going to be invited what will the application process look like? Will they just submit a PR here on GitHub? I'm not asking to add my stream right now as I am still working out the kinks as I learn the platform and how to effectively create content.

I understand this project was just created today, as it was mentioned on the Xamarin Show podcast.

**Comment by adilanchian** [comment]
I would love to know more about this process as well :). 

Awesome community!

**Comment by csharpfritz** [comment]
I'm going to create an issue template here for applying to join the team.  It should be simple to fill out, and we should be able to get back to you quickly.

The current requirements are on the README at the front of this repository.

**Comment by mgroves** [comment]
Hello! I just reached affiliate, and I think I meet all the other qualifications. I live code at least twice a week, plus other stuff like soldering, tech podcasting, and some gaming. Instead of opening a new issue, I thought I'd tack on to this issue, since I don't see an issue template for joining yet. https://www.twitch.tv/matthewdgroves

**Comment by qmacro** [comment]
Hello folks - like @mgroves I also thought it would be the right thing to do to add my comment to the end of this issue, hope that's OK with you all. I too am a Twitch affiliate and stream on my channel ([https://www.twitch.tv/qmacro99](https://www.twitch.tv/qmacro99)) regularly - weekly on Fridays and fortnightly on Wednesdays. I think I also meet the other [qualifications in the README](https://github.com/livecoders/Home#qualifications) too - would it be possible please to add me to this team? Thank you.

**Comment by timbeaudet** [comment]
I've been streaming almost every day for since mid-late 2017 and would like to to join the Team. I also found no way to join but found this issue and joining on the train of requesting here vs a new issue post? I do my best to stay positive, answer all questions and think I fit all other requirements; most of my streams are programming focused although on occasion I'll do art, business and marketing for my indie adventure. @themichaeljolley / @cmjchrisjones mentioned this to me.

Thanks for consideration!

**Comment by csharpfritz** [comment]
For all future applicants, please open a new issue with information about your stream.
