### ISSUE TITLE
Application for Membership

### ISSUE THREAD

**Issue by terrajobst** [livecoders/Home#178]
**What is the URL for your Twitch channel?**
https://twitch.tv/terrajobst

My recordings [go to you YouTube](https://www.youtube.com/playlist?list=PLRAdsfhKI4OWNOSfS7EUu5GRAVmze1t2y).

**What languages / frameworks / tools do you program in while streaming on Twitch?**
C#, .NET Core, Visual Studio Code

**Why do you write code on stream?**
I'm building a compiler from scratch. Many developers are intimidated by building a compiler and my goal is to de-mystify it while also providing insight into what a real-world production compiler will look like.

**What is your favorite moment from coding on stream?  Share a clip if one is available**
I have a small but very active community. It's so awesome to see PRs being submitted during my live stream 😄

**Comment by ConnerOrth** [comment]
Dear reviewer of this application,
I would like to endorse @terrajobst and his streams/vods.
They have been a tremendous source of inspiration and knowledge for both myself and a few of my colleagues and friends.
I've no doubt whatsoever that he is a positive addition to any (streaming) team.

Kind regards,
Just one of the people who truly looks forward to his streams/vods.

**Comment by Nirmal4G** [comment]
> What is your favorite moment from coding on stream?

https://clips.twitch.tv/BlindingHorribleConsoleFutureMan

**Comment by Aniel** [comment]
> What is your favorite moment from coding on stream?

https://clips.twitch.tv/FrigidSuavePrariedogKevinTurtle

@terrajobst does a great job explaining concepts!

**Comment by CBenghi** [comment]
Hello reviewers,
I take great pleasure in watching the incredible technical ability and clarity of thought that @terrajobst conveys in the videos that he publishes.
Please accept my warmest recommendation for his application to your collective.
Best regards,
Claudio

**Comment by ltrzesniewski** [comment]
This is basically the only developer stream I watch, from one of the developers of .NET itself, with a very cool topic that is nicely explained, and I cannot recommend @terrajobst highly enough. :+1:

**Comment by acolom** [comment]
I will be hard to express in English how good this stream is. 

Since the begining @terrajobst has explain how compilers work, but also has explained which approach is going to take to develope and most important **why is taking it**.

With his knowledge from other projects (compilers) guides all the viewers in the process. He also takes time to discuss community contribution and merge pull requests.

This channel is not only good for learning about compilers, it is also a bunch of masterclasses about how to code, use git, the C# language, .NET in general, tooling... But also about problem solving techniques and iterative coding, refining code,refactoring...

In last months he has also improved his streaming techniques, making an effort to answer questions from viewers.

> > What is your favorite moment from coding on stream?
https://youtu.be/xF-8rWeqV1A?list=PLRAdsfhKI4OWNOSfS7EUu5GRAVmze1t2y&t=70

**Comment by DualBrain** [comment]
This is a brain-dead-obvious-choice... watch any episode and it makes no sense why he wouldn't be accepted!

**Comment by csharpfritz** [comment]
That's a LOT of endorsements...  <sigh>   I'm going to have to approve... I _guess_

Welcome to the team!  Of COURSE...  Look for an email from Twitter with instructions to join the team and then I'll invite you to the private team Discord server to meet your new teammates
